api_extended_bundle:
    path: /product-models/{code}
    defaults: { _controller: pim_api.controller.product_model:deleteAction, _format: json }
    methods: [DELETE]
    prefix: /api/rest/v1
    requirements:
        code: .+

